/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#f9f9f9",
        "surface-dim": "#dadada",
        "surface-bright": "#f9f9f9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f3",
        "surface-container": "#eeeeee",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "on-surface": "#1a1c1c",
        "on-surface-variant": "#43474e",
        "inverse-surface": "#2f3131",
        "inverse-on-surface": "#f1f1f1",
        outline: "#73777f",
        "outline-variant": "#c3c6d0",
        "surface-tint": "#3f608b",
        primary: "#001833",
        "on-primary": "#ffffff",
        "primary-container": "#002d56",
        "on-primary-container": "#7596c4",
        "inverse-primary": "#a7c8fa",
        secondary: "#fdc008",
        "on-secondary": "#ffffff",
        "secondary-container": "#f9bd00",
        "on-secondary-container": "#6c5000",
        tertiary: "#1b1718",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#302b2c",
        "on-tertiary-container": "#999293",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#f9f9f9",
        "on-background": "#1a1c1c",
        "surface-variant": "#e2e2e2",
        "on-secondary-fixed": "#251a00",
        // Warm accent tones
        brass: {
          50: "#fdf8e8",
          100: "#f9edc5",
          200: "#f4dfa3",
          300: "#eccf7e",
          400: "#e4be59",
          500: "#d4af37",
          600: "#b8962e",
          700: "#9a7d25",
          800: "#7c641c",
          900: "#5e4b13",
        },
        // Cool steel tones
        steel: {
          50: "#f4f5f7",
          100: "#e2e4e8",
          200: "#c4c8d0",
          300: "#a0a6b2",
          400: "#7c8494",
          500: "#5d6575",
          600: "#4a5160",
          700: "#3a404d",
          800: "#2c313b",
          900: "#1e2229",
        },
      },
      borderRadius: {
        DEFAULT: "0",
        lg: "0",
        xl: "0",
        "2xl": "4px",
        "3xl": "8px",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        "stack-md": "40px",
        "stack-lg": "120px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "container-max": "1440px",
        gutter: "24px",
        "grid-gutter": "24px",
      },
      fontFamily: {
        "headline-xl": ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "headline-lg-mobile": ["Montserrat", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["IBM Plex Sans", "sans-serif"],
        "label-lg": ["IBM Plex Sans", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["72px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-xl": ["72px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "700" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.55", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "600" }],
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic": "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};